In [ ]:
import numpy as np


def pathdif(x,y):
  r=0
  if x<=y:
    r=(y+1)-x
  else:
    r=(x+1)-y
  return r

def need(strt,end,arr):
  for i in range(minboard, maxboard+1):
    if strt<=end:
      if arr[i][0] >= strt and arr[i][0] <= end:
        arr[i][1]=arr[i][1]+1
    else:
      if arr[i][0] >= end and arr[i][0] <= strt:
        arr[i][1]=arr[i][1]+1
  return arr


# def discalc(x,d,r):
#   for i in range(0, n):
#     if r[i][0]<=r[i][1]:
#       if r[i][0]<=x and r[i][0]>=x:
#         d[i]=d[i]-1
#     if r[i][0]>r[i][1]:
#       if r[i][0]>=x and r[i][0]<=x:
#         d[i]=d[i]-1
#   return d

def update(x,r,n):
  for i in range(0,n):
    if r[i][0]<=r[i][1]:
      if r[i][0]<=x and r[i][0]>=x:
        r[i][2]=r[i][2]-1
    if r[i][0]>r[i][1]:
      if r[i][0]>=x and r[i][0]<=x:
        r[i][2]=r[i][2]-1
  return r 




# def numerize():
#   n=int(input())
#   if n <= 1000:
#     return n
#   else:
#     print("Invalid Choice")
#     return numerize()


T = int(input('Number of test cases  :\n'))

if 1<= T <= 100:
  for tst in range(0, T):
    print("Test case no:",tst+1)
    k = int(input('Enter the number of adv: '))
    n = int(input('Enter the number of joggers: '))
    
    run= np.zeros([n, 3], dtype = int)
    # print(run)
    minboard=0
    maxboard=0
    if n <= 1000 and k >= 1:
      for i in range(0, n):
        x, y = input().split()
        run[i][0]= x
        run[i][1]= y
      # print(run)      
      minboard = np.min(run)
      maxboard = np.max(run)
      # print(minboard, maxboard)
      park= np.zeros([(maxboard+1)-minboard, 3], dtype = int)
      # print(park)
      x=0
      for i in range(minboard, maxboard+1):
        park[x][0]=i
        x=x+1
      # print(park)

      dist=np.zeros(n, dtype= int)
      for i in range(0, n):
        run[i][2] = pathdif(run[i][0],run[i][1])
      # print(dist)

      distresidue=dist
      
      for i in range(0, n):
        park=need(run[i][0],run[i][1],park)
      # print(park)

      for i in range(minboard, maxboard+1):
        if park[i][1] > 1:
          park[i][2]=1

      for i in range(0, n):   

      print(run)
      print(park)  



      



    else:
      print("Invalid Choice ")
else:
  print("Invalid Choice")

Number of test cases  :
1
Test case no: 1
Enter the number of adv: 5
Enter the number of joggers: 3
-3 4
2 12
4 5
[[-3  4  8]
 [ 2 12 10]
 [ 4  5  1]]
[[-3  1  0]
 [-2  1  0]
 [-1  1  0]
 [ 0  1  0]
 [ 1  1  0]
 [ 2  2  1]
 [ 3  2  1]
 [ 4  3  1]
 [ 5  2  1]
 [ 6  1  0]
 [ 7  1  0]
 [ 8  1  0]
 [ 9  1  0]
 [10  1  0]
 [11  1  0]
 [12  1  0]]
